### ISSUE TITLE
Two factor Authentication functionality disappeared in v7.7

### ISSUE THREAD

**Issue by sirnino** [ging/fiware-idm#109]
Hi all,
I've noticed that in version 7.7 the 2FA functionality disappeared from the _Settings_ page of the users despite it's not documented in the changelog.
I've an up and running instance of Keyrock 7.7 deployed on docker (**fiware/idm:FIWARE_7.7**).

**Comment by apozohue10** [comment]
Hi @sirnino, in release 7.0.0 of Keyrock it was decided to re-write all the code in NodeJS and we re-implemented the most important features leaving others developments as two-factor authentication for later. But, actually we have in mind to re-implement it in the future!

**Comment by sirnino** [comment]
Hi @apozohue10, thank you for replying.
As far as I saw, the Two factor authentication whas available until the v7.5.1 (I've it up and running and the functionalty is there). It disappeared in v7.7.

Anyway, do you have a time plan for the release of the two factor authentication?

Thank you again.

**Comment by apozohue10** [comment]
It was a little bug. On the page of settings was the two factor authentication option inherited from the
previous openstack-based Keyrock web interface and we remove from the view because it is not supported in the NodeJs version of Keyrock yet. 

If you need it, you can implement it and make a PR and we will be glad to accept it!

**Comment by sirnino** [comment]
Ok thank you.
