### ISSUE TITLE
Is there any way to invalidate a token?

### ISSUE THREAD

**Issue by caballero03** [ging/fiware-idm#12]
I have been working on my own instance of Keyrock IDM and learning a lot about how to integrate my API with it. 

I am having difficulty determining how to "log out" a user. If my application is run by a single user per browser it works fine but if one user logs out and another tries to log in before the last user's token has expired, they just get redirected as the user previously logged in. 

Our plan is to allow web (remote) access to our API but also have terminals at our facility for users to use to access their account. We would need a properly functioning "log out" mechanism.

Is there a way to invalidate a token? Is there a way to log out a user? All I have tried gives me a "invalid csrf token" error message. Is there a way to acquire a valid CSRF token for my logout link to work properly?

Thank you in advance.

**Comment by apozohue10** [comment]
Hi @caballero03,

OAuth2 does not support log out mechanisms. However you could manage some configuration, for instance you can edit config file to reduce the expiration time of OAuth2 tokens to be lower.

As for the first problem, the user should make log out from IdM Portal if another user wants to use the same browser.

**Comment by caballero03** [comment]
Thank you apozohue10,

I understand that OAuth2 does not have a logout mechanism but there is the concept of revoking/disabling tokens in some OAuth2 implementations.

There does not appear to be a way to "logout" from the IdM Portal atfer being redirected to the callback endpoint with the auth code.

If my app could query the IdM for a csrf token, I could call the DELETE /auth/logout endpoint and the IdM session will be deleted. Am I mistaken?

The desired behavior would be to allow the current user to click logout and then the subsequent user will be presented with a login prompt from the IdM Portal instead of being logged right back into the app with the last guys stale token and identity. 

Again, this is only an issue in a shared browser situation. Any ideas would be greatly appreciated.

**Comment by apozohue10** [comment]
Hi @caballero03 
We haven't implemented an endpoint to generate CSRF tokens, but I think your idea would work. But as you have said is only an issue in a shared browser situation. However, if you find any solution, we will try to add it and make it configurable, so that people could use it if they have the same issue as you.

**Comment by vwroad87** [comment]
I did find a work-around for my needs but it is less than ideal. For development it is going to work. It may also work well in the long run but it is not clear yet.

All I did was change the expires setting to 60 seconds instead of an hour within the config.session section of the config.js file. This appears to work in my application (for now) and also when using the IdM UI. When using the later, you just need to be brief and log-in a lot. :-D

Considering that I plan to use the IdM's native UI as little as possible in favor of the API, I think this solution could even work with a shorter expires value for the session.

Thank you for your input regarding this special case.
