### ISSUE TITLE
Unable to receive confirmation email

### ISSUE THREAD

**Issue by flopezag** [ging/fiware-idm#23]
I am using the last version of the IdM - Keyrock (latest, v7.0.0). When I try to register an user based on yahoo email, the confirmation email is never received in yahoo. Additionally, if I check the functionality in gmail and outlook servers, the confirmation email is received but marked as SPAM mail.

**Comment by tmontanaro** [comment]
Unfortunately I noticed the same problem!
You can, in any case, use the software buy following this instructions:
1. try to login using `admin@test.com` and `1234`
Proceed only if it logs in (otherwise the problem could be another one)
2. logout and try to register a new user
3. After seeing the message that says "An email was sent ..." enter the mysql database:
    `sudo docker exec -it fiwareidm_mysql_1 mysql -uroot -p`  
     (fiwareidm_mysql_1 is the name of the docker container that you can get through sudo docker container ls) (pass: idm)
4. Then create a user to let you manage the database from outside
    ```
    CREATE USER 'newUser'@'%' IDENTIFIED BY 'newPassword';
    GRANT ALL PRIVILEGES ON *.* TO 'newUser'@'%' WITH GRANT OPTION;
    FLUSH privileges;
    ```
5. enter the `idm` database and verify that your user was correctly inserted:  
    `use idm; Select * from user;`
6. change to `true` the values of "enabled" and "admin" (if necessary) and apply changes

In this way I was able to use the Idm!

**Comment by aalonsog** [comment]
Closed due to inactivity.
