### ISSUE TITLE
Oauth2 API presents bugs

### ISSUE THREAD

**Issue by joansrios** [ging/fiware-idm#58]
i'm using the idm 7.5.0 Docker  container, and when i want to create an application using the Oauth2 API, or i want to assign a permission or a role using the API, the result is an internal server error 500.

The API can detect when the application creation request lacks of the redirect uri, but when this is  included always presents the error.

**Comment by apozohue10** [comment]
We have checked the API and you are right there were some requests that results in an internal server error 500. Fixes have been included in master branch and would be included in the next release.
The apiary has been updated:
 - There was a mistake in create application body request in token_types attribute
 - Role user and role organization relationships in applications is now POST instead of PUT

I have also checked the error related with redirect uri when create an application and actually i don't have any problems. Maybe your error has been fixed with the latest commit.
