### ISSUE TITLE
Make a user an admin using API

### ISSUE THREAD

**Issue by pabSec** [ging/fiware-idm#74]
I'm trying to fetch all users authorized in an application including username, email and roles with a defined role `Administrator` into the application but it seems to be impossible (If not, please tell me how).

So my approach now (only for this use case) is to make admin users (In IDM) to those who below to this mentioned application with `Administrator` role in order to get `/users` using the idm API.

Am I lost and is this possible or I should build a service between my front app and the idm or fork the project?

**Comment by apozohue10** [comment]
Hi @pabSec 

Currently, it is possible to list all users but I don't know it this suits with your particular case.
First you need to obtain the relationship between the role id and de user id of the application as described in [apiary](https://keyrock.docs.apiary.io/#reference/keyrock-api/authorized-users-in-an-application/list-users-in-an-application).
Once you have obtained this relationship, you need to create an api token with admin user credentials of idm (currently only admin users could retrieve info about users) so that you can make a request for each user id (checking from the list obtained in the previous step if role id is Administrator) and obtain its user info.
